Fix issues with moduleResolution NodeNext
haruaki07/phosphor-svelte pull request #16
Opened 2023-12-22 14:00 UTC by OfficialCRUGG

Fixes #15

2023-12-23 02:04 UTC, haruaki07 commented
I was able to reproduce this type error, it's happened when I'm importing icons with named export.

2024-03-27 14:28 UTC, haruaki07 requested changes

2024-04-12 16:01 UTC, haruaki07 requested changes

2024-04-12 16:01 UTC, haruaki07 commented on tests/template.test.js
> +      .toEqual(`import { SvelteComponent, IconProps } from "./shared.js";
```suggestion
      .toEqual(`import type { SvelteComponent, IconProps } from "./shared.d.ts";
```

2024-04-12 16:03 UTC, haruaki07 approved these changes

2024-04-12 16:04 UTC, merged

2024-04-15 22:37 UTC, OfficialCRUGG commented
Sorry for not fixing this myself. Completely forgot about it. 😅
Will this be included in a release soon? It's quite essential for projects where this issue occured.